[package]
name = "rust-viz"
version = "0.1.0"
edition = "2021"
description = "Lightweight Rust data visualization using Serde serialization and CnD"
license = "MIT OR Apache-2.0"
keywords = ["visualization", "data", "serde", "graph", "lightweight"]
categories = ["visualization", "data-structures"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde-value = "0.7"
