[package]
name = "json_data_instance_export"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde-value = "0.7"
tera = "1.17.0"
warp = "0.3"
tokio = { version = "1", features = ["full"] }
