[package]
name = "rust-viz"
version = "0.1.0"
edition = "2021"
description = "Lightweight Rust data visualization using Serde serialization and CnD"
license = "MIT OR Apache-2.0"
keywords = ["visualization", "data", "serde", "graph", "lightweight"]
categories = ["visualization", "data-structures"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.9"
serde-value = "0.7"
tera = "1.17.0"
once_cell = "1.0"
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["full", "extra-traits"] }

[dev-dependencies]
trybuild = "1.0"
